### PR TITLE
ported to .Net 4.0

### PR DESCRIPTION
**Pull request by michaelholly**

### CODE REVIEW

**Comment by andersnm** [comment]
Hi,

Do you have a spesific use case in mind for this? 

Because I'm not sure this is needed? If your app is net40 and references the ExcelDataReader nuget, it should resolve to the net20 binaries of ExcelDataReader, which afaict behaves the same as this new proposed net40 target with the SharpZipLib dependency.

**Comment by michaelholly** [comment]
Hi,
first of all, thank you for your quick response.
I use Visual Studio 2010 with .Net 4.0 as target framework. If I use the net20 binaries it leads to the compile error "Missing compiler required member System.Runtime.CompilerServices.ExtensionAttribute..ctor", which results from  src/ExcelDataReader.DataSet/Portable/ExtensionAttribute.cs.  So I skipped this part for net40.

Best regards.

**Comment by andersnm** [comment]
Hi,

Ok, if remembering correctly I tested the ExtensionAttribute only in VS2015, where it generated a harmless build warning. A quick test in VS2017 produces no warning. Although it sounds like older VSes produce an error instead ;(

I believe this PR can be reduced to changing a line in ExcelDataReader.DataSet.csproj:

The line that says:
```xml
<TargetFrameworks>net20;net45;netstandard2.0</TargetFrameworks>
```

Can be changed to:
```xml
<TargetFrameworks>net20;net35;netstandard2.0</TargetFrameworks>
```

Thoughts:

- net35 is the earliest version supporting extension methods
- net35 binary is covered by the net45 tests
- dependant net40 apps will get the net20 reader dll and net35 dataset dll

For purposes of attribution, are you interested in redoing the PR with only this change?

**Comment by michaelholly** [comment]
Hi,
thanks, I will try this and create a new PR.

**Comment by michaelholly** [comment]
Created a new pull request with the proposed changes.

**Pull request closed without merging**
