### PR TITLE
Added column names support.

### PR DESCRIPTION
**Pull request by Jhayphal**

### CODE REVIEW

**Comment by wizardgsz** [comment]
Hey good job but are you sure about this? 

if (_columnNames.ContainsKey(columnName))
                    throw new InvalidOperationException("Columns names ambiguous.");

**Comment by Jhayphal** [comment]
Hey. Thank you. How else? If the column names are repeated, it will be impossible to unambiguously retrieve the value by name.

**Comment by Jhayphal** [comment]
> Hey good job but are you sure about this?
> 
> if (_columnNames.ContainsKey(columnName))
> throw new InvalidOperationException("Columns names ambiguous.");

Hey. Thank you. How else? If the column names are repeated, it will be impossible to unambiguously retrieve the value by name.

**Comment by wizardgsz** [comment]
Yeah, I know it but in Excel it is allowed to have "duplicated" column names, so...

**Comment by Jhayphal** [comment]
> Yeah, I know it but in Excel it is allowed to have "duplicated" column names, so...
> 
> Edit: I read that latest Excel 365 has "smart tables" where column names are "unique" but only for this feature. Older versions still have duplicated columns :)

I understand that Excel allows you to enter the same column names. But the user must also understand that he needs to specify different names so that he can work by name :)

I don't see anything wrong with that.

**Comment by Jhayphal** [comment]
> Yeah, I know it but in Excel it is allowed to have "duplicated" column names, so...
> 
> Edit: I read that latest Excel 365 has "smart tables" where column names are "unique" but only for this feature. Older versions still have duplicated columns :)

You may not fully understand my code.
I added the ReadHeader method to the interface.
If you do not call it yourself, then everything will work as before - methods for working with column names will throw NotSupportedException. Those. all the code currently using your library will work as before.
Anyone who needs to use columns with names should understand that they cannot have the same name.

**Pull request closed without merging**
