### PR TITLE
Fix for reading rows without the "r" attribute

### PR DESCRIPTION
**Pull request by zoranchaushev**
We've encountered an xlsx file, where the content of the worksheets/sheetN.xml file has "row" and "c" elements without the "r" attribute. This caused an exception when trying to read the file. However, we can open it in Excel without any problems.

Here's an example of the content in the sheetN.xml files:

&lt;sheetData&gt;
        &lt;row ht="22.5" customHeight="1"&gt;
            &lt;c s="117" /&gt;
            &lt;c s="20" /&gt;
            &lt;c s="20" /&gt;
            &lt;c s="20" /&gt;
            &lt;c s="20" /&gt;
            &lt;c s="20" /&gt;
            &lt;c s="20" /&gt;
            &lt;c s="20" /&gt;
            &lt;c s="101" /&gt;
        &lt;/row&gt;
        &lt;row ht="22.5" customHeight="1"&gt;
            &lt;c s="52" /&gt;
            &lt;c s="7" /&gt;
            &lt;c s="7" /&gt;
            &lt;c s="7" /&gt;
            &lt;c s="7" /&gt;
            &lt;c s="7" /&gt;
            &lt;c s="7" /&gt;
            &lt;c s="7" /&gt;
            &lt;c s="77" /&gt;
        &lt;/row&gt;
&lt;/sheetData&gt;

### CODE REVIEW

**Comment by wizardgsz** [comment]
We also further investigate a similar issue.
Read this topic please https://github.com/ExcelDataReader/ExcelDataReader/issues/91

**Comment by wizardgsz** [comment]
Meanwhile I verified your fix using the enclosed file where row numbering were "forced" :+1: 
It's a test case created to verify my implementation starting from issue https://github.com/ExcelDataReader/ExcelDataReader/issues/97.
Thanks a lot.

[RowNumber5.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/202226/RowNumber5.xlsx)

**Comment by wizardgsz** [comment]
If possibile, please could you kindly commit to your pull request this test?

[Issue_NoStyles_NoRAttribute.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/204639/Issue_NoStyles_NoRAttribute.zip)

Excel.Tests\App.config

`<add key="xTest_Issue_NoStyles_NoRAttribute" value="Test_Issue_NoStyles_NoRAttribute.xlsx" />
`

Excel.Tests.4.5\Excel.Tests.4.5.csproj
```
<Content Include="Resources\Test_Issue_NoStyles_NoRAttribute.xlsx">
  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</Content>
```

Excel.Tests\Excel.Tests.csproj
```
<Content Include="..\Excel.Tests.4.5\Resources\Test_Issue_NoStyles_NoRAttribute.xlsx">
  <Link>Resources\Test_Issue_NoStyles_NoRAttribute.xlsx</Link>
  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</Content>
```

Excel.Tests\ExcelOpenXmlReaderTest.cs
```
/// <summary>
/// Sheet has no [dimension] and/or no [cols].
/// Sheet has no [styles].
/// Each row [row] has no "r" attribute.
/// Each cell [c] has no "r" attribute.
/// </summary>
[TestMethod]
public void Issue_NoStyles_NoRAttribute()
{
	using (IExcelDataReader excelReader = 
		ExcelReaderFactory.CreateOpenXmlReader(Helper.GetTestWorkbook("xTest_Issue_NoStyles_NoRAttribute")))
	{
		excelReader.IsFirstRowAsColumnNames = false;
		DataSet result = excelReader.AsDataSet();

		Assert.IsTrue(result.Tables.Count > 0);
		Assert.AreEqual(39, result.Tables[0].Rows.Count);
		Assert.AreEqual(27, result.Tables[0].Columns.Count);
		Assert.AreEqual("ROW NUMBER 5", result.Tables[0].Rows[4][4].ToString());

		excelReader.Close();
	}
}
```

**Comment by zoranchaushev** [comment]
Done.

**Comment by andersnm** [comment]
Looks like this was merged with #139. Feel free to reopen if mistaken

**Pull request closed without merging**
