### PR TITLE
Patch for fixing issue #97

### PR DESCRIPTION
**Pull request by 5kym0nk3y**
This is my patch for fixing issue #97 Failed to read XLSX. Basically, the cell element in the xml is "<x:c r="0" t="str">" instead of "<x:c r="A1" t="str">". This is my first pull request ever. :-) Please let me know if there is anything I can improve.

### CODE REVIEW

**Comment by Ian1971** [comment]
Do the unit tests still pass?

**Comment by 5kym0nk3y** [comment]
4 unit tests failed which are all Issue_Encoding_1520_Test. 6 tests
skipped. 160 passed. Is the encoding test related to the language setting
on my machine?

**Comment by Ian1971** [comment]
I can't remember exactly but there were a couple that fail. I think they are commented as such

**Comment by andersnm** [comment]
This was fixed in #228. Thanks

**Pull request closed without merging**
