### PR TITLE
Must always scan all cells to determine field count

### PR DESCRIPTION
**Pull request by appel1**
The dimension record can be incorrect. 

Fixes issue #2.

### CODE REVIEW

**Comment by appel1** [comment]
Because of this we could probably simplify InitializeSheetRead/ReadWorkSheetGlobals quite a lot. For sheets with lots of cells implementing FindMaxReferencedColumn in a way that do not create an object for each record might also be a good idea.

**Comment by andersnm** [comment]
If I read this correctly, then you could remove the last call to `_stream.Read();` from FindMaxReferencedColumn(), and then revert all the changes in ReadNextBlock() ?

I think ReadNextBlock() was easier to follow before this, because you could see the single call to _stream.Read(). Now its using _stream.LastRead" for the first chunk, and you have to trace it back to FindMaxReferencedColumn() where it comes from.

**Comment by appel1** [comment]
I don't think we can because then we'd miss the first cell if there is no dimension or row records. ReadWorkSheetGlobals reads until the first cell in that case. 

Since the stream is in-memory FindMaxReferencedColumn could be moved into ReadWorkSheetGlobals instead. And there we can keep track of the position of the record before the first cell record if we ever read that far and seek to it before returning. Then we could remove the whole LastRecord ugliness.

**Comment by andersnm** [comment]
Nice, I like this. Do you think we can simplify further and just seek to sheet.DataOffset before each loop (i.e globals, max-columns, rows), and eliminate the previousPosition stuff? 

Looks like each loop just looks at the chunks its interested in anyway, and we get slightly leaner code in exchange for a few extra iterations over ignored chunks. (sorry for being pedantic about this but since we're first looking at this code :bowtie:)

(I also noticed AppVeyor automatically built and tested the last PR commit, which is sweet)

**Comment by appel1** [comment]
Usually this means that we'll do the work to read and create record instances for the sheet header (around 15 + <number of columns> records) and the row records for the first cell block twice. But considering that we read all cell records twice the cost for that is relatively low. 

If it is a problem we might be able to improve performance a little by using a specialized read in ReadWorkSheetGlobals that does not create record instances.

**Pull request merged**
