### PR TITLE
Fixed ConvertFromOATime range bug.

### PR DESCRIPTION
**Pull request by SteveHolle**
Added range checking to ConvertFromOATime in Excel.Core.Helpers.cs to prevent exception when out of range value is in spreadsheet.  Now sets the value to them max + or - depending on which sign is out of range.

### CODE REVIEW

**Comment by SteveHolle** [comment]
Sorry it took me so long to get back to this.  What is the best way for me to address this issue?  Should I continue to work from my current fork or abandon this fork and create a new from the root.  I'm still a noob at this.

Thanks.

**Comment by Ian1971** [comment]
I think carry on from current fork and submit new pull request

On Tue, Jun 16, 2015 at 4:42 PM, Stephen Holle <notifications@github.com>
wrote:

> Sorry it took me so long to get back to this. What is the best way for me
> to address this issue? Should I continue to work from my current fork or
> abandon this fork and create a new from the root. I'm still a noob at this.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/pull/20#issuecomment-112475299>
> .
>



-- 

Ian Cox
C.T.O.

Release  Mobile

m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.releasemobile.com

Registered in England.  Number 06323661

**Comment by SteveHolle** [comment]
I can't seem to open a new pull request on this branch?

**Comment by Ian1971** [comment]
Does this help?
http://stackoverflow.com/questions/16748115/how-to-modify-github-pull-request

**Comment by andersnm** [comment]
If this is still a problem, can you please submit a new PR against the develop branch which also includes a test demonstrating the problem (i.e a spreadsheet with out of range date). There is probably a spec for "OADate" somewhere which says what the correct values for these constants should be.

**Pull request closed without merging**
