### PR TITLE
fix issue 578.

### PR DESCRIPTION
**Pull request by Andreybonfi**
Based on issue [578](https://github.com/ExcelDataReader/ExcelDataReader/issues/578)
Add Inplementation of  GetValues(object[] values)

- Return real count of readed Cells
-  Always return reading row from excel 

It seems to me the best solution is to always return data to the user even if he asks for more than what exists in the Excel Row.

### CODE REVIEW

**Comment by Andreybonfi** [comment]
However, the solution that I implemented, when using this library, seems to me to make the library easy to use. using While, it seems to me not the best solution. I suggest the following approach

This is how I go to the library:
```cs
using (ExcelReader excel = new ExcelReader(FileInfo.Path))
     {
            foreach (var Row in excel)
                {
                 <...>
                 }
      }
```
For use, I just implemented the following code
```cs
public IEnumerator<ExcelRow> GetEnumerator()
        {
            while (Read())
            {
                var CurrentRow = ReadRow();
                yield return CurrentRow;
            }
        }
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }


        public object[] ReadRow(int width = 100)
        {
            int max = FieldCount > width ? width : FieldCount;

            var row = new object[max];

            for (int i = 0; i < max; i++)
            {
                row[i] = RowCells[i]?.Value;
            }

            return row;
        }

```
I think width  must become part of the constructor (Excel reader). That the user can define the maximum readable width of their files. In general, if there is an empty string, create an array of 16.000 items, bad idea.

**Comment by appel1** [comment]
Thanks. 

The implementation should follow the contract as specified which I think you've already done. I'll take closer look after the holidays. 

I don't think the ReadRow helper adds enough value to add to the core library.

**Comment by appel1** [comment]
Could you add tests for the other supported file formats as well?

**Comment by Andreybonfi** [comment]
Good afternoon, I'm not sure if you saw the changes.  But I have added tests for supported files.

**Pull request merged**
