### PR TITLE
Assorted refactorings and optimizations:

### PR DESCRIPTION
**Pull request by Lehonti**
- Removed unnecessary usings
- Removed block nesting levels in a few places
- Made BuiltinNumberFormat.Formats explicitly read-only, as it's never modified
- Made Helpers.EscapeRegex compiled

### CODE REVIEW

**Comment by wizardgsz** [comment]
> Are there any measurable performance improvements with changing to RegexOptions.Compiled?
> 
> Not sure how useful IReadOnlyDictionary is for a private field used in one place, it just adds overhead. Once FrozenDictionary becomes available maybe it makes sense to use that where available instead.

It **should** help if you compile once and run/use them more times.

**Comment by Lehonti** [comment]
> Not sure how useful IReadOnlyDictionary is for a private field used in one place, it just adds overhead. Once FrozenDictionary becomes available maybe it makes sense to use that where available instead.

This counts as a refactoring rather than an optimization. It's intended to make the intent clearer (that is, the programmer knows that it will never be modified).

As for the overhead, I don't think there's any significant overhead. Look at the implementation of `Dictionary<,>` here: https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/shared/System/Collections/Generic/Dictionary.cs

There are not even that many interface-specific methods or properties for `IReadOnlyDictionary<,>`, and if there were any overhead, it would consist of an extra method call.

**Comment by appel1** [comment]
For a method that is potentially called for every cell in very big documents I don't think the added overhead is worth the slight increase in readability. 

``` 
|          Method |     Mean |     Error |    StdDev |
|---------------- |---------:|----------:|----------:|
| TryGetInterface | 7.896 ns | 0.0441 ns | 0.0391 ns |
|     TryGetClass | 5.303 ns | 0.0478 ns | 0.0424 ns |
```

**Comment by appel1** [comment]
For the regex it makes sense though. Possibly we could even add a net70 target and use [GeneratedRegex] in that case to avoid the startup cost.

```
|           Method |                    S |        Mean |     Error |    StdDev |
|----------------- |--------------------- |------------:|----------:|----------:|
|          Replace |                    a |    38.19 ns |  0.123 ns |  0.115 ns |
|  ReplaceCompiled |                    a |    35.04 ns |  0.101 ns |  0.085 ns |
| ReplaceGenerated |                    a |    32.21 ns |  0.069 ns |  0.058 ns |
|          Replace | abc_x(...)006A_ [80] | 2,613.63 ns | 25.726 ns | 22.806 ns |
|  ReplaceCompiled | abc_x(...)006A_ [80] | 1,946.21 ns | 21.622 ns | 19.167 ns |
| ReplaceGenerated | abc_x(...)006A_ [80] | 1,907.85 ns | 20.042 ns | 17.767 ns |
|          Replace | rbtke(...)64evg [42] |    46.37 ns |  0.085 ns |  0.076 ns |
|  ReplaceCompiled | rbtke(...)64evg [42] |    45.53 ns |  0.086 ns |  0.076 ns |
| ReplaceGenerated | rbtke(...)64evg [42] |    40.15 ns |  0.092 ns |  0.082 ns |
|          Replace |    set_x006A_gdrgdfg |   338.98 ns |  2.921 ns |  2.589 ns |
|  ReplaceCompiled |    set_x006A_gdrgdfg |   282.08 ns |  2.161 ns |  2.021 ns |
| ReplaceGenerated |    set_x006A_gdrgdfg |   285.06 ns |  5.764 ns | 11.644 ns |
```

**Comment by Lehonti** [comment]
But ok @appel1 , I changed it back to `Dictionary<,>`

**Review by andersnm — APPROVED** [review]

**Pull request merged**
