### PR TITLE
Merged Cells

### PR DESCRIPTION
**Pull request by Nodrog-82**
Handle Merged cells

### CODE REVIEW

**Comment by andersnm** [comment]
Hi! There's definitely some good work here; never got around to investigate the specs for these fields myself.

At least the parsing bits look good, but I'm not sure if we want to return the same value for merged cells? I had an idea to expose information about merged cells through some sort of GetColSpan()/GetRowSpan() API per cell possibly, so that it's easy to generate f.ex HTML tables. But not entirely sure if that makes sense. Gotta (find time to) study the code a bit closer before I can make any real suggestions

**Comment by Nodrog-82** [comment]
Hello. I know other APIs do not auto merge, but expose the list of merged cells. The main difference here is that they handle read and write whereas I saw this as a way to cleanly read all data from excel for import into an application so copying the value is in my case ideal, apologies if I have over simplified it's purpose.

Would you prefer me to just expose the merge cells list and leave the exist cells alone?

**Comment by andersnm** [comment]
Just a couple thoughts: The current class `MergedCell` is perhaps slightly more specific than it needs to be, and could be simplified and renamed to `CellRange`. Can keep the constructors and public properties, but the source stuff looksn't needed. Then we can use the same class for f.ex named ranges later

And so the list of merged cells could be exposed through a new property `CellRange[] MergedCells` on IExcelDataReader, through the ExcelDataReader class from the IWorksheet implementations

Thanks!

**Comment by Nodrog-82** [comment]
I believe the changes requested have been done.

**Pull request merged**
